### ISSUE TITLE
[Checklist] GA Microsoft.Identity.Web

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-identity-web#517]
### 1. Functionally complete 
Library supports  major service features)
- [x] Web apps, Web apis, MVC, Razor, Blazor (hosted and not)
- [x] SingleOrg, AnyOrg, B2C
- [x] Calling Web APIs, Calling Graph or nothing
- [x] Templates for major scenarios and variations available in .NET 5

Out of Scope - We can explain these to customers:
- Integration with easy auth
- Identity framework

### 2. Documentation 
Quick starts based on the templates (Running sample should not be more than few steps)

   - [x] [ASP.NET Core Web App that signs-in users (from template)](https://github.com/AzureAD/microsoft-identity-web/issues/520)
   - [x] ASP.NET Core Protected Web API (from template)
   - [x] Web app signs-in user and calls web apis scenario landing page (using GraphService and/or IDownstream API)
   - [x] Web app signs-in user scenario landing page
   - [x] Protected web APIs scenario landing page
   - [ ] Wiki migrated to docs.ms with links from the wiki pages to the corresponding docs.ms page.

### 3. Tutorials, Samples and reference docs

  - [x] Ensure tutorials exist for the scenarios based on the templates
  - [x] Ensure reference docs exist
  - [x] Ensure samples exist under https://azure.microsoft.com/en-us/resources/samples/
  - [x] Samples repositories must specify how to run sample
  - [x] Running sample should not be more than few steps

### 4. Packaging and discoverability

 - [x] Links to docs, source code repository, release notes
 - [x] Library should follow semantic versioning
	
### 5. Maintenance & support 

 - [x] CI/CD and instructions should exist
 - [x] Source code builds without errors and warnings
 - [x] Release notes published with each major and minor release
 - [x] Library provides logging and error handling for debugging purposes
 - [x] Library provides basic telemetry to collect data on usage
 - [x] Production level support:
    - [x] ICM process in place (path and rotations)
    - [x] Security escalation process in place

### 6. Open source 
- [x] Source code is public and open to contributions
- [x] Licensing – Must contain an OSI compliant license. Currently the SDKs use MIT license
- [x] Readme must have information on  
   - [x] Library description
   - [x] Pre-requisites if any
   - [x] How to build library
   - [x]  How to run tests
   - [x]  Link to Azure docs, samples
   - [x]  How to contribute code

### 7. Semantic Versioning
- [x] Libraries are built using semantic versioning principles
- [x] Major versions are released when there is either net new developer value or breaking changes
- [x] Minor versions are for all new feature updates
- [x] Revisions are for bug fixes 

### 8. Support SLA
Our current support mechanism also follows Azure all up
- [x] Major versions are supported for 12 months /1 year after the release of the next major version
- [x] Minor versions older than N-1 are not supported.
		○ Minor versions are bugfixes or features with non-breaking (additive) API changes.  It is expected apps can upgrade.  Therefore, we will not patch old minor versions of the library, and we should ask app owners to confirm that an issue repros on the latest minor version before spending time investigating an issue.
	
### 9. Triage Feedback & Telemetry from Early Adopters
- [x] GitHub issues and PRs are actively triaged.
		○ GA blockers are addressed.  A GA blocker would be a material regression in the end to end experience or a gap in the convergence MVP. 
- [x] No stale issues without response or open PRs sitting past 3 months.
- [x]  Stack overflow issues are actively triaged.
- [x] GA blockers are addressed.  A GA blocker would be a material regression in the end to end experience or a gap in the convergence MVP.
- [x] No stale issues without response or open PRs sitting past 3 months
- [ ] Adoption Program in place
     - [x] GA blockers tracked in TFS (1P) or GitHub (3P) 
     - [x] CxP driving  3P adoption plan 
     - [x] PM team driving 1P adoption plan
